# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3D2DrF5ltSur3vlMblOYnAQ4sKb", email: "apriac@athos.ca", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfbWljcm9zb2Z0L2ltZ18zRDJEckpzSXA4VGpLMG9HMmduVFdOV1JPZHEifQ", username: "Alexandre Priac"})
}